### PR TITLE
Added support to render GraphiQL as per express version.

### LINKED ISSUE #8: Add graphiql
The express version has it built in, would be awesome have!

### PR DESCRIPTION
**Pull request by rogchap**
fixes #8

### CODE REVIEW

**Comment by chasevida** [comment]
Hey, was just trying out your PR but for some reason I keep running into server errors. The example in the readme should just work as long as there is a valid schema right?

**Comment by rogchap** [comment]
It should... Can you post the server errors you are getting?

**Comment by chasevida** [comment]
Hey, it may be my implementation but I'm unsure sorry. This is the error I get, when I add `graphiql: true` to the registration options.

```
<path>/lib/index.js:238
    throw validation.error;
    ^

ValidationError: child "query" fails because ["query" must be a Function, "graphiql" is not allowed]
... etc (joi validation issues)
```

**Comment by rogchap** [comment]
Looks like two errors here.... 1) you `query` is not "formated" correctly. 
And 2) I forgot to add the graphiql property in the Joi validation check for the options.
I can fix issue 2, but you'll need to sort out 1) :smile:

**Comment by rogchap** [comment]
Ok... that's not the issue, as I've added the correct validation: 
https://github.com/rogchap/hapi-graphql/commit/296e2eef0a59c250ec6017db91023ab105e0ab86#diff-1fdf421c05c1140f6d71444ea2b27638R22 
Can you post your implementation code?

**Comment by chasevida** [comment]
Thanks, I thought it was most likely to do with my implementation. Will post it here when I get a chance, thanks.

**Comment by chasevida** [comment]
I think perhaps my issues are coming from my lack of experience with graphql overall sorry. Does this PR add the ability to run _graphiql_ when you hit the route `/graphql`?

**Comment by chasevida** [comment]
The linked gist is what I was attempting before trying to preview `graphi` on the path `/graphql`.

https://gist.github.com/chasevida/f4f2e33f18cfa5b1619f

**Comment by rogchap** [comment]
My bad.... sorry.
I missed out an import statement. Added to PR.

**Comment by chasevida** [comment]
Cheers, that's working now. I'll play with it a little but seems to be good.

**Comment by jsonmaur** [comment]
Is this ever going to be merged? Would be really useful to have :)

**Comment by rogchap** [comment]
@SimonDegraeve seems to have left the room!??

**Comment by chasevida** [comment]
Perhaps he'd consider adding some contributors to help develop/maintain this.

**Comment by denneulin** [comment]
maybe you should publish your own version on npm @rogchap

**Pull request merged**
