### PR TITLE
Features/setup test and ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Setup test infrastracture, and write the first ones :)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
> $ touch this :)

**Comment by AdrieanKhisbe** [comment]
> `$ touch` #   :)

(If you wanna help to maintain it, don't hesitate to tell me :) )

**Comment by chasevida** [comment]
Hey, just pulled your fork down to run the tests and I don't get any coverage when they are run?

```
Coverage: 0.00% (0/0)
```

Stoked you've added tests for this though, hoping this and a few of the other PRs see some progress. 

Cheers.

**Comment by AdrieanKhisbe** [comment]
Hey @chasevida, 
mmmmm.
Strange, gonna check this out in the days to come. 
Thanks for the heads up!

**Comment by AdrieanKhisbe** [comment]
@chasevida, had a look, and indeed no coverage stated.
I suspect this has to do with `lab-babel`. 
Will require deeper investigation.

**Comment by chasevida** [comment]
All good, I've had some strange things going on with `lab-babel` lately too. Did you ever get a coverage report, just curious how much these tests cover. Thanks.

**Comment by AdrieanKhisbe** [comment]
Honestly I don't even remember :/
(but maybe travis remind for me ;))

**Comment by AdrieanKhisbe** [comment]
travis gave no clue, but at least spot some problem in the package.json :)

**Comment by AdrieanKhisbe** [comment]
closing but feel free to ping me if you want to reopen&merge it
cc @SimonDegraeve

**Pull request closed without merging**
